# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
    - releases/*
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install git-buildpackage
    sudo apt-get install debhelper debmake
  displayName: 'Install Dependencies'

- script: |
    make -p build
    gbp buildpackage \
      --git-debian-branch=main \
      --git-ignore-new \
      --git-ignore-branch \
      -uc -us \
      --git-export-dir=build \
      --git-tarball-dir=build
  displayName: 'Build Debian Package'

- task: GithubRelease@0
  displayName: 'Attach debian package to release'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  inputs:
    gitHubConnection: github.com_stuwilkins
    repositoryName: NSLS-II/artwork
    assets: build/*.deb
    action: edit
    target: '$(Build.SourceVersion)'
    tag: '$(Build.SourceBranchName)'
    addChangeLog: false
    assetUploadMode: replace